name: CI & Deploy Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew clean bootJar -x test --stacktrace

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: build/libs/*.jar


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: spring-boot-jar

    - name: List files for debug
      run: ls -R

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Link Railway project
  

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up
