name: CI Build Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - run: chmod +x ./gradlew

      - run: ./gradlew clean bootJar -x test --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: build/libs/*.jar
